version: "3.8"



services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: go-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=gogogo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-gogogo}
    ports:
      - 1111:80
    restart: always
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:-2565}:${PORT:-2565}
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://hgqvnwpr:F50_9sky10ii2OVedWnRhdJWvm66iSW7@tiny.db.elephantsql.com/hgqvnwpr?sslmode=disable}
    container_name: golang-backend
    restart: always


