version: "3.2"

networks:
  integration-test-example:


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - $PWD:/go/src/target
    networks:
      - integration-test-example
    ports:
      - "2565:2565"
    env_file:
      - docker.env
    depends_on:
      - postgres
  postgres:
    image: postgres:12.12
    container_name: golang_postgres
    environment:
      - POSTGRES_USER=gopher
      - POSTGRES_PASSWORD=Gopher123
      - POSTGRES_DB=postgres
    networks:
      - integration-test-example
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    restart: on-failure
    ports:
      - "9999:5432"
    expose:
      - "9999"