version: "3.8"

networks:
  golang-docker:

services:
  database:
    image: postgres:13
    container_name: go-postgres
    ports:
      - 1112:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRES_DB=${DB_DATABASE:-golang}
      - POSTGRES_SSLMODE=disable
    restart: always
  pgadmin4:
    image: dpage/pgadmin4 #ตอนเพิ่ม database เพื่อดูใช้ ipv4 แทน localhost
    container_name: go-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=gogogo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-gogogo}
    ports:
      - 1111:80
    restart: always
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:-2565}:${PORT:-2565}
    #environment:
     #  - DATABASE_URL=postgres://${DB_USERNAME:-root}:${DB_PASSWORD:-root}@postgres:5432/${DB_DATABASE:-golang}?sslmode=disable
#      - PORT=2565
    container_name: golang-backend
    depends_on:
      - database
    restart: always


